version: "3.9"
services:
      postgres:
            image: docker.io/postgres:9.5
            privileged: true
            environment:
            - POSTGRES_USER=netdisco
            - POSTGRES_PASSWORD=netdisco
            ports:
            - "5432:5432"


      netdisco:
            #image: irasnyd/netdisco:latest
            image: paglipay/netdisco:2.05
            privileged: true
            environment:
            - NETDISCO_ADMIN_USER=admin
            - NETDISCO_ADMIN_PASS=admin
            - NETDISCO_DB_HOST=postgres
            links:
            - postgres:db
            ports:
            - "5100:5000"
            sysctls:
            - "net.ipv6.conf.all.disable_ipv6=0"
             
